version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: wortal_db
    ports:
      - "5432:5432"

  service-app:
    build: ./service
    ports:
      - "8080:8080"
    environment:
      database.host: database
      DB_URL: jdbc:postgresql://database/wortal_db
    depends_on:
      - database

  client-app:
    build: ./client
    ports:
      - "8081:8081"